회원가입 기능 구현
f-lab-edu/somoim-clone pull request #37
Opened 2022-05-22 08:07 UTC by realbrush

Email과 password(암호화) 정보로 회원가입을 하는 기능 구현.

2022-05-22 09:56 UTC, JinXuanT commented
니엄마 😎

2022-05-22 09:57 UTC, JinXuanT commented
니아빠 😎

2022-05-23 01:44 UTC, f-lab-joseph commented on src/main/java/com/somoim/service/UserService.java
> +        user.setPassword(passwordEncrypt.hashPassword(user.getPassword()));
테스트 코드가 없습니다. + user 의 생성 및 값 세팅의 책임은 user 도메인 안에 있는 것이 좋지 않을까요 ? 테스트에도 더 용이할 것으로 생각됩니다.
ex ) User.create(....) 등등

2022-05-26 01:11 UTC, realbrush commented on src/main/java/com/somoim/service/UserService.java
> +        user.setPassword(passwordEncrypt.hashPassword(user.getPassword()));
제가 이 댓글을 확인하지 못하고 일단 SetPassword에 바로 암호화를 적용하였습니다. 원준님께서 말씀하신 사항이 저도 궁금한 부분이었는데 해당 내용이 맞을까요?

2022-05-26 04:49 UTC, f-lab-joseph requested changes
unit test

2022-05-26 04:49 UTC, f-lab-joseph commented on src/main/java/com/somoim/config/DatabaseConfig.java
> +public class DatabaseConfig {
향후에 readonly datasource(replication) 를 추가해서 reaonly transaction / transaction 에서 각각 사용하게 한다면 어떻게 변경 되어야 할까요 ?

2022-05-26 04:49 UTC, f-lab-joseph commented on src/main/java/com/somoim/dto/User.java
> +        PasswordEncrypt passwordEncrypt = new PasswordEncrypt();
passwordEncrypt 는 component 인데 여기서 생성해서 사용하시는게 적절치 않지 않을까요 ?

2022-05-26 04:49 UTC, f-lab-joseph commented on src/main/java/com/somoim/service/UserService.java
> +        user.setDisband(false);
entity 의 속성을 service 에서 침범해서 설정하는 것이 적절하지 않은 것 같은데 user domain 내부에서 값을 설정하는 것이 좋지 않을까요 ?

2022-05-26 04:49 UTC, f-lab-joseph commented on src/main/java/com/somoim/service/UserService.java
> +    public void insertUser(User user) {
별도의 DTO 가 존재하지 않네요. service layer 이하로는 도메인으로, 그 위에서는 DTO 로 통신할 수 있도록 만드는 것이 어떨까요 ? 
뷰 계층에서 필요로 하는 데이터가 도메인과 상이한 경우가 있는데, 이것을 변환해주는 계층을 service layer 로 정의하고요

2022-05-26 04:49 UTC, f-lab-joseph commented on src/main/java/com/somoim/util/PasswordEncrypt.java
> +        return BCrypt.hashpw(password, BCrypt.gensalt());
spring 의 password encoder 를 사용하는 것은 어떨까요 ?

2022-05-26 04:49 UTC, f-lab-joseph commented on src/test/java/com/somoim/service/UserServiceTest.java
> +class UserServiceTest {
Spring boot test 가 아닌 unit test 는 존재하지 않나요 ?

2022-05-26 13:26 UTC, wj-dominic commented on src/main/java/com/somoim/service/UserService.java
> +    public void insertUser(User user) {
@f-lab-joseph
service layer를 기준으로 위 아래 데이터를 동일하게 사용하더라도 각 계층에 맞춰 분리해서 일관된 구조로 사용한다고 생각하면 될까요?

2022-05-29 15:35 UTC, f-lab-joseph commented on src/main/java/com/somoim/service/UserService.java
> +    public void insertUser(User user) {
네, 그렇게 한번 개선해보면 좋을 것 같습니다

2022-06-03 03:22 UTC, realbrush commented on src/main/java/com/somoim/config/DatabaseConfig.java
> +public class DatabaseConfig {
각 datasource에 해당하는 config 클래스와 routing config 클래스를 각각 생성하여 설정한 후 기능에 맞는 datasource를 사용할 수 있도록 해야 합니다.

2022-06-03 03:22 UTC, realbrush commented on src/main/java/com/somoim/dto/User.java
> +        PasswordEncrypt passwordEncrypt = new PasswordEncrypt();
@f-lab-joseph 
네 Service에서 PasswordEncoder를 사용하도록 변경하였습니다.

2022-06-03 03:22 UTC, realbrush commented on src/main/java/com/somoim/service/UserService.java
> +        user.setDisband(false);
@f-lab-joseph 
네 dto 내 static createUser 함수를 통해서 내부에서 값을 설정할 수 있도록 변경하였습니다.

2022-06-03 03:23 UTC, realbrush commented on src/main/java/com/somoim/service/UserService.java
> +    public void insertUser(User user) {
@f-lab-joseph 
dto와 dao를 분리하여 계층에 맞춰 사용할 수 있도록 구조를 변경하였습니다.

2022-06-03 03:24 UTC, realbrush commented on src/main/java/com/somoim/util/PasswordEncrypt.java
> +        return BCrypt.hashpw(password, BCrypt.gensalt());
@f-lab-joseph 
네 해당 PasswrodEncrypt은 제거하고 spring-security의 passwordEncoder로 적용했습니다.

2022-06-03 03:27 UTC, realbrush commented on src/test/java/com/somoim/service/UserServiceTest.java
> +class UserServiceTest {
@f-lab-joseph 
아닙니다. Springboot는 모든 Bean을 로드하여 테스트를 실행하므로, Mockito를 사용한 유닛테스트로 변경하였습니다.

2022-06-03 14:31 UTC, realbrush commented on src/main/java/com/somoim/service/UserService.java
> +    public User selectMember(String email) {
> 

이미 수정된 사안이었으나 다시 한 번 체크하니 이번 기능에서는 불필요하여 해당 기능을 삭제하였습니다.

2022-06-03 14:32 UTC, realbrush commented on src/main/java/com/somoim/model/dao/User.java
> +    public void createUser(String email, String password, String createAt) {
> createUser에서 User가 만들어질 것 같은 이름을 가졌는데 지금은 setUser 같은 용도로 사용된 것 같습니다~

Build 패턴을 사용하여 해당 메소드의 기능을 대체하였습니다.

2022-06-03 14:33 UTC, realbrush commented on src/main/java/com/somoim/service/UserService.java
> +        newUser.createUser(user.getEmail(),
> 이 부분은 다시 User 도메인 생성의 책임이 UserService로 온 것 아닐까요?

Builder 패턴으로 대체하여 해당 문제를 해결하였습니다.

2022-06-05 10:06 UTC, f-lab-joseph commented on src/main/java/com/somoim/exception/DuplicateEmailException.java
> +public class DuplicateEmailException extends RuntimeException{
indent

2022-06-05 10:06 UTC, f-lab-joseph commented on src/main/java/com/somoim/model/dao/User.java
> +    private boolean disband;
primitive type 대신 래퍼 타입을 사용해주세요.

2022-06-05 10:06 UTC, f-lab-joseph commented on src/main/java/com/somoim/model/dao/User.java
> +    public User(String email, String password, String createAt) {
createAt 은 date type 이여야 할 것 같은데, String 을 사용하신 이유가 있을까요 ?

2022-06-05 10:06 UTC, f-lab-joseph commented on src/main/java/com/somoim/service/UserService.java
> +    SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:sss");
쓰레드 세이프 한가요 ?

2022-06-05 12:35 UTC, wj-dominic commented on src/main/java/com/somoim/model/dao/User.java
> +    private boolean disband;
디버깅을 해보니 mybatis에서 쿼리 결과를 리턴할 때 래퍼 타입을 리턴 하던데
언박싱과 컬럼이 null인 경우를 고려해서 래퍼 타입을 사용하는 것이 맞을까요?

2022-06-05 14:06 UTC, f-lab-joseph commented on src/main/java/com/somoim/model/dao/User.java
> +    private boolean disband;
네, 게다가 프리미티브 값은 기본값이 있어서, 의도와 다른 동작을 하게 될 수 있습니다.

2022-06-06 06:54 UTC, realbrush commented on src/main/java/com/somoim/model/dao/User.java
> +    public User(String email, String password, String createAt) {
db의 datetime 타입과 바인딩 문제가 생길 것 같아 String으로 처리했는데 찾아본 결과 특정 mybatis 버전부터는 date type과 바인딩 되는 것을 확인하여 Date 정보는 모두 date type(LocalDateTime)으로 변경하였습니다.

2022-06-06 06:54 UTC, realbrush commented on src/main/java/com/somoim/model/dao/User.java
> +    public User(String email, String password, String createAt) {
> createAt 은 date type 이여야 할 것 같은데, String 을 사용하신 이유가 있을까요 ?

db의 datetime 타입과 바인딩 문제가 생길 것 같아 String으로 처리했는데 찾아본 결과 특정 mybatis 버전부터는 date type과 바인딩 되는 것을 확인하여 Date 정보는 모두 date type(LocalDateTime)으로 변경하였습니다.

2022-06-06 06:54 UTC, realbrush commented on src/main/java/com/somoim/model/dao/User.java
> +    public User(String email, String password, String createAt) {
db의 datetime 타입과 바인딩 문제가 생길 것 같아 String으로 처리했는데 찾아본 결과 특정 mybatis 버전부터는 date type과 바인딩 되는 것을 확인하여 Date 정보는 모두 date type(LocalDateTime)으로 변경하였습니다.

2022-06-06 06:55 UTC, realbrush commented on src/main/java/com/somoim/service/UserService.java
> +    SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:sss");
스레드 세이프하지 않습니다. 해당 사항은 수정하여 반영하였습니다.

2022-06-08 00:39 UTC, merged